### ISSUE TITLE
URL Change

### ISSUE THREAD

**Issue by zerowebcorp** [kingster/Way2SMS-API#1]
Hi

The SMS POST url seems like changed.

It is way2sms.com/jsp/stp2p.action 

May be you should try updating the script with correct url

**Comment by iAnuj** [comment]
Line number?

**Comment by zerowebcorp** [comment]
https://github.com/kingster/Way2SMS-API/blob/master/way2sms-api.php#L71

**Comment by iAnuj** [comment]
Still not working on my side. Possible changes on Line 58, 75 too.

**Comment by gowthamantoni** [comment]
I gave my correct way2sms credentials. But it says Invalid login. Please help.

**Comment by kingster** [comment]
Way2SMS has added captcha verification, hence this api wont work any more. I will update when I can figure out some way to overcome the same.

**Comment by gowthamantoni** [comment]
Thanks a lot for your reply. Please do update me if/when it starts working.

Best,
Gowtham.

**Comment by rkumar670** [comment]
@kingster  did you get something?

**Comment by hirenchauhan2** [comment]
@kingster please update the script. 
Thank you!

**Comment by siddu244** [comment]
please update the script.

**Comment by suyashbansal** [comment]
I made it working again. @gowthamantoni @rkumar670 @harry008 @siddu244
https://github.com/suyashbansal/Way2SMS-API

**Comment by kingster** [comment]
Hi Suyash

Nice! Send me a pull request and I will merge it to this repo :)

**Comment by suyashbansal** [comment]
Thanks
I just posted a pull request. :+1:

**Comment by ashif-ismail** [comment]
Check my Working Repo at https://github.com/SheikhZayed/WAY2SMS-API.git,
Try the sample app : http://ancient-lowlands-31895.herokuapp.com/
@getvivekv @iAnuj @kingster @gowthamantoni @harry008 @rkumar670

**Comment by kingster** [comment]
Thanks Suyash

I have verified your changes and merged them into master :+1:  

Thanks again for the contribution.
