### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by Ak-sky** [kingster/Way2SMS-API#10]
Getting the following below error
PHP Notice:  Undefined property: WAY2SMSClient::$jstoken in /home/pi/Way2SMS-API/way2sms-api.php on line 108

**Comment by kingster** [comment]
Hello!

How are you using the library? Could you share some more details?

**Comment by kingster** [comment]
Looks like there was a case-issue with $jstoken, could you use the updated library and verify if the issue is resolved?
