### ISSUE TITLE
It stopped Working

### ISSUE THREAD

**Issue by sunnysharma03** [kingster/Way2SMS-API#13]
The api seems to have stopped working since a week , I've been using it for the past months . Please resolve this and make this work again ! Thanks

**Comment by ShahryarRaza** [comment]
it seems that the api has stopped working. please fixed as soon as possible. thankyou

**Comment by suyashbansal** [comment]
I've sent a pull request with the updated code. 😄

**Comment by b1n0d** [comment]
suyashbansal :) Thank you so much buddy. Its working.
