### ISSUE TITLE
Its not working anymore

### ISSUE THREAD

**Issue by VivekTodur** [kingster/Way2SMS-API#18]
It stopped working again two weeks back. Could somebody troubleshoot and correct the code

Thanks

**Comment by FelixSekar** [comment]
It worked for me today.
Check if the php tag is closed in your copy of 'way2sms-api.php' file.

**Comment by jatin69** [comment]
It throws no error as such, but I can't receive the SMS. 
what to do?

**Comment by p1pahare** [comment]
it worked for me.

**Comment by nawafgantare** [comment]
Idk why its not working for you guys.I have been using it for past 3-6 months and its working flawless.

**Comment by FelixSekar** [comment]
@jatin69 have you checked whether the php tag is closed in your copy of 'way2sms-api.php' file ?

**Comment by jatin69** [comment]
@FelixSekar yes it was closed. It didn't throw any error. Tried every check. But still no message.

**Comment by FelixSekar** [comment]
@jatin69 check the phone numbers, you cant put 91 in front of it.

**Comment by prezine** [comment]
Fatal error: Uncaught Error: Call to undefined method Auth::sendWay2SMS() in C:\xampp\htdocs\GreencycleFin\Class\GC_Auth.php:63 Stack trace: #0 C:\xampp\htdocs\GreencycleFin\Module\inviteUser.php(7): Auth->InviteFriend('08179685649') #1 {main} thrown in C:\xampp\htdocs\GreencycleFin\Class\GC_Auth.php on line 63

Exactly what i keep getting after a long hour of trying to fix codes bug? I'm feeling sick, HELP!

**Comment by prezine** [comment]
Oh it's indians sef'... Prrrr!
