### ISSUE TITLE
Repeated Login and Logout

### ISSUE THREAD

**Issue by YashKumarVerma** [kingster/Way2SMS-API#7]
Say a user has to send messages with different content to different people. This can be done using loop, but the problem is that, whenever the function is called, it logs into the website, send the message and then logsout every time. This is acceptable for 2-3 messages but for say about 30 messages, it becomes a very extensive process. 
Is there any way to skip the re-login and re-logout every-time ?

Cheers !

**Comment by kingster** [comment]
There isn't any direct method right now, but you could modify the function to accept pairs of number and message and send it accordinly.

You would need to change here  [way2sms-api.php#L81](https://github.com/kingster/Way2SMS-API/blob/master/way2sms-api.php#L81)

The clean solution would be to refactor this into multiple functions and separate out login/logout from send function

**Comment by kingster** [comment]
I have refactored the library so that you can reuse components. Now login once and send as many as you want (Refer to the example function). 

_Remember to put delay in between otherwise your ip can be detected as spammer by way2sms and blocked_

**Comment by YashKumarVerma** [comment]
Thanks ! This is the best way2sms api I have ever used. By the way is there any API for 160/2 ?
